### ISSUE TITLE
import issues

### ISSUE THREAD

**Issue by krutarth0** [taoyilee/pyECG#3]
pip install pyECG went successful but import gave me an error,

code:
 from pyecg import ECGRecord

error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyecg\__init__.py", line 6, in <module>
    from pyecg.dataset import RecordTicket, ECGDataset
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyecg\dataset.py", line 12, in <module>
    from ishneholterlib import Holter
  File "C:\ProgramData\Anaconda3\lib\site-packages\ishneholterlib\__init__.py", line 9, in <module>
    from PyCRC.CRCCCITT import CRCCCITT
ModuleNotFoundError: No module named 'PyCRC' 

PS:  I  also installed PyCRC but this problem remains the same. can this be a version issue?

**Comment by alessandropadrinofficial** [comment]
Same issue of @krutarth0

**Comment by TUJIALAN** [comment]
> pip install pyECG went successful but import gave me an error,
> 
> code:
> from pyecg import ECGRecord
> 
> error:
> Traceback (most recent call last):
> File "", line 1, in
> File "C:\ProgramData\Anaconda3\lib\site-packages\pyecg__init__.py", line 6, in
> from pyecg.dataset import RecordTicket, ECGDataset
> File "C:\ProgramData\Anaconda3\lib\site-packages\pyecg\dataset.py", line 12, in
> from ishneholterlib import Holter
> File "C:\ProgramData\Anaconda3\lib\site-packages\ishneholterlib__init__.py", line 9, in
> from PyCRC.CRCCCITT import CRCCCITT
> ModuleNotFoundError: No module named 'PyCRC'
> 
> PS: I also installed PyCRC but this problem remains the same. can this be a version issue?

The install package for 'pycrc' named pythoncrc
Try this:
>pip install pythoncrc

**Comment by Prophet0fRegret** [comment]
The issue persists for me even after "pip install pythoncrc" . Any other suggestions?

**Comment by pemocarlo** [comment]
Commit 95f854c90713ffb370917f20b11e4d9c1ed6d5c6 introduced a fix, but it was not pushed to Pypi. What worked for me was :
first
`pip uninstall PyCRC `
and then
`pip install pythoncrc`

**Comment by melodyre** [comment]
> Commit [95f854c](https://github.com/taoyilee/pyECG/commit/95f854c90713ffb370917f20b11e4d9c1ed6d5c6) introduced a fix, but it was not pushed to Pypi. What worked for me was :
> first
> `pip uninstall PyCRC `
> and then
> `pip install pythoncrc`

I uninstalled pycrc and installed pythoncrc. but the problem exists

**Comment by MohMsh** [comment]
same issue still exists, any updates?
